

public class IPrincipal extends javax.swing.JFrame {

   
    public IPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        pilaProductos = new javax.swing.JMenu();
        pilaInteger = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        listasPersona = new javax.swing.JMenu();
        listasString = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        colasCliente = new javax.swing.JMenu();
        colasNombre = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenu1.setText("Pilas");

        pilaProductos.setText("Productos");
        pilaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilaProductosMouseClicked(evt);
            }
        });
        jMenu1.add(pilaProductos);

        pilaInteger.setText("Enteros");
        pilaInteger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilaIntegerMouseClicked(evt);
            }
        });
        jMenu1.add(pilaInteger);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listas");

        listasPersona.setText("Persona");
        listasPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listasPersonaMouseClicked(evt);
            }
        });
        jMenu2.add(listasPersona);

        listasString.setText("Colores");
        listasString.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listasStringMouseClicked(evt);
            }
        });
        jMenu2.add(listasString);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Colas");

        colasCliente.setText("Cliente");
        colasCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colasClienteMouseClicked(evt);
            }
        });
        jMenu3.add(colasCliente);

        colasNombre.setText("Nombre");
        jMenu3.add(colasNombre);

        jMenuBar1.add(jMenu3);

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
       System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void pilaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilaProductosMouseClicked
        PilaProducto producto = new PilaProducto();
        escritorio.add(producto);
        producto.setVisible(true);
    }//GEN-LAST:event_pilaProductosMouseClicked

    private void pilaIntegerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilaIntegerMouseClicked
        VPilaInteger enteros = new VPilaInteger();
        escritorio.add(enteros);
        enteros.setVisible(true);
    }//GEN-LAST:event_pilaIntegerMouseClicked

    private void listasPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listasPersonaMouseClicked
        VListasPersona personas = new VListasPersona();
        escritorio.add(personas);
        personas.setVisible(true);
    }//GEN-LAST:event_listasPersonaMouseClicked

    private void listasStringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listasStringMouseClicked
        VListasString colores = new VListasString();
        escritorio.add(colores);
        colores.setVisible(true);
    }//GEN-LAST:event_listasStringMouseClicked

    private void colasClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colasClienteMouseClicked
       VColasCliente cliente = new VColasCliente();
       escritorio.add(cliente);
       cliente.setVisible(true);
    }//GEN-LAST:event_colasClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu colasCliente;
    private javax.swing.JMenu colasNombre;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu listasPersona;
    private javax.swing.JMenu listasString;
    private javax.swing.JMenu pilaInteger;
    private javax.swing.JMenu pilaProductos;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
