public class VListasString extends javax.swing.JInternalFrame {

    ListasEnlazadasColores colores;
    public VListasString() {
        this.colores= new ListasEnlazadasColores();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        color = new javax.swing.JTextPane();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Eposcicion = new javax.swing.JButton();
        Enombre = new javax.swing.JButton();
        Rinverso = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Iinicio = new javax.swing.JButton();
        Iposcicion = new javax.swing.JButton();
        Ifinal = new javax.swing.JButton();
        Efinal = new javax.swing.JButton();
        Einicio = new javax.swing.JButton();
        Rimprimir = new javax.swing.JButton();
        Rbuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        poscicion = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(color);

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Insertar");

        jLabel2.setText("Eliminar");

        Eposcicion.setText("Poscicion");
        Eposcicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EposcicionActionPerformed(evt);
            }
        });

        Enombre.setText("Nombre");
        Enombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnombreActionPerformed(evt);
            }
        });

        Rinverso.setText("Inverso");
        Rinverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RinversoActionPerformed(evt);
            }
        });

        jLabel3.setText("Reportes");

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane8.setViewportView(texto);

        jLabel4.setText("Color");

        Iinicio.setText("Inicio");
        Iinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IinicioActionPerformed(evt);
            }
        });

        Iposcicion.setText("Poscicion");
        Iposcicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IposcicionActionPerformed(evt);
            }
        });

        Ifinal.setText("Final");
        Ifinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IfinalActionPerformed(evt);
            }
        });

        Efinal.setText("Final");
        Efinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfinalActionPerformed(evt);
            }
        });

        Einicio.setText("Inicio");
        Einicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EinicioActionPerformed(evt);
            }
        });

        Rimprimir.setText("Imprimir");
        Rimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RimprimirActionPerformed(evt);
            }
        });

        Rbuscar.setText("Buscar");
        Rbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbuscarActionPerformed(evt);
            }
        });

        jLabel11.setText("Poscicion");

        jScrollPane9.setViewportView(poscicion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                          .addGap(22, 22, 22)
                                          .addComponent(jLabel1)
                                          .addGap(59, 59, 59)
                                          .addComponent(jLabel2)
                                          .addGap(31, 31, 31)
                                          .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                          .addComponent(jLabel4)
                                                          .addGap(18, 18, 18)
                                                          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                          .addComponent(jLabel11)
                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                          .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                          .addContainerGap()
                                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                  .addComponent(Iinicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addComponent(Ifinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                  .addComponent(Iposcicion))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                          .addGap(4, 4, 4)
                                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                  .addComponent(Einicio)
                                                                  .addComponent(Efinal))
                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                  .addGroup(layout.createSequentialGroup()
                                                                          .addComponent(Rimprimir)
                                                                          .addGap(18, 18, 18)
                                                                          .addComponent(regresar))
                                                                  .addComponent(Rbuscar)))
                                                  .addGroup(layout.createSequentialGroup()
                                                          .addGap(6, 6, 6)
                                                          .addComponent(Enombre))
                                                  .addGroup(layout.createSequentialGroup()
                                                          .addComponent(Eposcicion)
                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                          .addComponent(Rinverso)))))
                      .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addGap(0, 0, Short.MAX_VALUE)
                      .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addContainerGap()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                      .addGap(18, 18, 18)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel11)
                                          .addGap(6, 6, 6))
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                      .addGap(18, 18, 18)
                      .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                      .addGap(4, 4, 4)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                          .addComponent(Einicio)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(Efinal))
                                .addGroup(layout.createSequentialGroup()
                                          .addComponent(Iinicio)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(Ifinal))
                                .addGroup(layout.createSequentialGroup()
                                          .addComponent(Rbuscar)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                  .addComponent(Rimprimir)
                                                  .addComponent(regresar))))
                      .addGap(9, 9, 9)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Iposcicion)
                                .addComponent(Eposcicion)
                                .addComponent(Rinverso))
                      .addGap(10, 10, 10)
                      .addComponent(Enombre))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void EposcicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EposcicionActionPerformed
        colores.eliminarEnPosicion(Integer.parseInt(poscicion.getText()));
        texto.setText("Eliminado con exito");

    }//GEN-LAST:event_EposcicionActionPerformed

    private void EnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnombreActionPerformed
        texto.setText(colores.elminarPorNombre(color.getText()));

    }//GEN-LAST:event_EnombreActionPerformed

    private void RinversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RinversoActionPerformed
        texto.setText(colores.contenidoListaInverso());
    }//GEN-LAST:event_RinversoActionPerformed

    private void IinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IinicioActionPerformed
        colores.insertarAlPrincipio(color.getText());
        texto.setText("Añadido con exito");
    }//GEN-LAST:event_IinicioActionPerformed

    private void IposcicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IposcicionActionPerformed
        colores.insertar(color.getText(), Integer.parseInt(poscicion.getText()));
        texto.setText("Añadido con exito");
    }//GEN-LAST:event_IposcicionActionPerformed

    private void IfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IfinalActionPerformed
        colores.insertarAlFinal(color.getText());
        texto.setText("Añadido con exito");
    }//GEN-LAST:event_IfinalActionPerformed

    private void EfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfinalActionPerformed
        if(colores.contenidoLista()=="")
            texto.setText("No hay nada");
        else {
            colores.eliminarUltimo();
            texto.setText("Eliminado con exito");
        }
    }//GEN-LAST:event_EfinalActionPerformed

    private void EinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EinicioActionPerformed
        if(colores.contenidoLista()=="")
            texto.setText("No hay nada");
        else {
            colores.eliminarPrimero();
            texto.setText("Eliminado con exito");
        }
        texto.setText(
            colores.eliminarUltimo());
    }//GEN-LAST:event_EfinalActionPerformed

    private void RimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RimprimirActionPerformed
        texto.setText(colores.contenidoLista());
    }//GEN-LAST:event_RimprimirActionPerformed

    private void RbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbuscarActionPerformed
        texto.setText(colores.buscarPorNombre(color.getText()));
    }//GEN-LAST:event_RbuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Efinal;
    private javax.swing.JButton Einicio;
    private javax.swing.JButton Enombre;
    private javax.swing.JButton Eposcicion;
    private javax.swing.JButton Ifinal;
    private javax.swing.JButton Iinicio;
    private javax.swing.JButton Iposcicion;
    private javax.swing.JButton Rbuscar;
    private javax.swing.JButton Rimprimir;
    private javax.swing.JButton Rinverso;
    private javax.swing.JTextPane color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane poscicion;
    private javax.swing.JButton regresar;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
